#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
# exec uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'
exec python manage.py runserver 0.0.0.0:8000
