# Generated by Django 4.0.8 on 2024-01-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_tags_alter_category_options_video_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, to='videos.tags'),
        ),
    ]
