# Generated by Django 3.2.16 on 2022-10-15 01:11

import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
        ('student', '0002_alter_student_user'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInTutorCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tutor_course', to='student.student')),
                ('tutor', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tutor_course', to='tutor.tutor')),
            ],
            options={
                'unique_together': {('tutor', 'student')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
