# Generated by Django 3.2.16 on 2022-10-17 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tutors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_tutor', to='tutor.tutor'),
        ),
    ]
