# Generated by Django 3.2.16 on 2022-10-15 04:32

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_user'),
        ('course', '0003_auto_20221015_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentintutorcourse',
            name='student',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_tutor_course', to='student.student'),
        ),
    ]
