# Generated by Django 3.2.16 on 2022-10-17 00:42

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
        ('course', '0004_alter_course_tutors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='course',
            field=auto_prefetch.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_users', to='course.course'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='tutor',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_tutor_course', to='tutor.tutor'),
        ),
    ]
