# Generated by Django 3.2.16 on 2022-10-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        ('course', '0005_auto_20221017_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='course_tasks', to='task.Task'),
        ),
    ]
