# Generated by Django 3.2.16 on 2022-10-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_classroom_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='new',
            new_name='is_new',
        ),
        migrations.AddField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
