# Generated by Django 3.2.16 on 2022-10-15 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
        ('student', '0003_student_course'),
        ('course', '0006_rename_studentintutorcourse_studentsintutorcourse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentsintutorcourse',
            unique_together={('tutor', 'course')},
        ),
    ]
