# Generated by Django 3.2.16 on 2022-10-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_course'),
        ('course', '0007_alter_studentsintutorcourse_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsintutorcourse',
            name='student',
        ),
        migrations.AddField(
            model_name='studentsintutorcourse',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='student_tutor_course', to='student.Student'),
        ),
    ]
