# Generated by Django 3.2.16 on 2022-10-19 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_coursecategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='tutors',
            new_name='tutor',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.coursecategory'),
        ),
    ]
