# Generated by Django 3.2.16 on 2022-10-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_tutor_task_course'),
        ('course', '0008_auto_20221015_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tasks',
            field=models.ManyToManyField(related_name='course_tasks', to='task.Task'),
        ),
    ]
