# Generated by Django 3.2.16 on 2022-10-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_course_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
