# Generated by Django 3.2.16 on 2022-10-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_course_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
