# Generated by Django 3.2.16 on 2022-10-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_tutor_task_course'),
        ('course', '0011_alter_course_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tasks',
        ),
        migrations.AddField(
            model_name='studentsintutorcourse',
            name='tasks',
            field=models.ManyToManyField(related_name='course_tasks', to='task.Task'),
        ),
    ]
