# Generated by Django 3.2.16 on 2022-10-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
