# Generated by Django 3.2.16 on 2022-10-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_coursecategory_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='courses',
            field=models.ManyToManyField(to='course.Course'),
        ),
    ]
