# Generated by Django 3.2.16 on 2022-10-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_alter_coursecategory_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hours_per_class',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
