# Generated by Django 3.2.16 on 2022-10-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20221015_0524'),
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='courses',
            field=models.ManyToManyField(to='course.Course'),
        ),
    ]
