# Generated by Django 3.2.16 on 2022-10-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20221019_0734'),
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='courses',
            field=models.ManyToManyField(related_name='tutor_courses', to='course.Course'),
        ),
    ]
