# Generated by Django 4.1.2 on 2022-10-17 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tags_blog_date_updated_blog_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='date_updated',
        ),
    ]
