# Generated by Django 4.1.2 on 2022-10-17 16:23

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_slug_alter_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, size=[500, 300], upload_to='blog_img/'),
        ),
    ]
