# Generated by Django 4.1.2 on 2022-10-30 10:52

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_alter_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="JPEG",
                keep_meta=True,
                quality=100,
                scale=None,
                size=[850, 300],
                upload_to="blog_img/",
            ),
        ),
    ]
