# Generated by Django 4.1.2 on 2022-10-21 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_blog_options_alter_category_options_and_more"),
        ("blog", "0013_alter_blog_image"),
    ]

    operations = []
