#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


exec celery -A config.celery_app worker -l INFO
# exec watchfiles celery.__main__.main --args '-A config.celery_app worker -l INFO -Q media'
