# Generated by Django 3.2.16 on 2022-10-19 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_customuser_profile_pic'),
        ('home', '0004_alter_customuser_gender'),
    ]

    operations = [
    ]
