# Generated by Django 3.2.16 on 2022-10-16 19:30

import auto_prefetch
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title of the course', max_length=125)),
                ('slug', models.SlugField(blank=True, max_length=125, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=10)),
                ('task_file', models.FileField(blank=True, null=True, upload_to='tasks/')),
                ('due_date', models.DateField()),
                ('course', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_task', to='course.course')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
