# Generated by Django 4.1.2 on 2022-10-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_tasksubmission_delete_task_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
