# Generated by Django 4.1.2 on 2022-10-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_tasksubmission_date_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='mark_earned',
            field=models.IntegerField(blank=True),
        ),
    ]
