# Generated by Django 4.1.2 on 2022-10-26 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_tasksubmission_task_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='mark_earned',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='task_file',
            field=models.FileField(upload_to='task_file/'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='tasks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
    ]
