# Generated by Django 4.1.2 on 2022-10-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_tasksubmission_mark_earned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='mark_earned',
            field=models.IntegerField(null=True),
        ),
    ]
