# Generated by Django 3.2.16 on 2022-10-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20221015_0524'),
        ('student', '0003_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(blank=True, to='course.Course'),
        ),
    ]
