#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput
python /app/manage.py migrate
python /app/manage.py generatesuperuser

# exec /usr/local/bin/gunicorn config.asgi --bind 0.0.0.0:5000 --chdir=/app -k uvicorn.workers.UvicornWorker
# exec uvicorn config.asgi:application --host 0.0.0.0:5000 --reload --reload-include '*.html'
exec python manage.py runserver 0.0.0.0:5000
